### ISSUE TITLE
Use larger scale for route caclulation

### ISSUE THREAD

**Issue by tjoneslo** [makhidkarun/traveller_pyroute#1]
When doing the final route drawing for the trade maps, multiply the final trade value `self.galaxy.stars[start][end]['trade']` by 10/3 before (see `StatCaclulation.trade_to_btn` or `HexMap.trade_line(line 366 / 373)` to get an average, not a minimum trade.

**Comment by CyberiaResurrection** [comment]
@tjoneslo , is this still a problem?

**Comment by tjoneslo** [comment]
No. This can be closed. Random thought from a decade ago.
