### ISSUE TITLE
Where is WikiReview defined?

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#11]
This is AWOL from the imports in WikiUploadPDF.py - at least my IDE couldn't find it.

Is this something along the lines of #7 - something that for whatever reason just didn't end up committed?

I tripped over this when I was going through the codebase and squaring up one bit of PEP8 formatting, so I'm not sure how I can test this one.

**Comment by tjoneslo** [comment]
Yes, another thing that got missed.

**Comment by tjoneslo** [comment]
Ok, pushed that up as well.

**Comment by CyberiaResurrection** [comment]
Yeah, it's up, so closing this.
