### ISSUE TITLE
What invariants characterise trade route generation?

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#16]
What logical predicates must all hold for a given trade route run for it to have a non-zero chance of being correct?  These checks would be assertions (ie, pass-or-die) - if a checked assertion doesn't hold, bomb the run immediately.

Which invariants are checked in a normal vs a debug run is a separate question.

Off the top of my head:
- All trade and passenger volumes must be non-negative.
- Galaxy-level trade must equal the sum of all sectors' internal and external trade.
- Galaxy-level passenger totals must equal the sum of all sectors' passenger totals.
- Galaxy-level trade must equal the sum of all allegiances' internal and external trade.
- Galaxy-level passenger totals must equal the sum of all allegiances' passenger totals.
- A sector's internal trade must not be smaller than the sum of its subsectors' internal trade.

Apart from non-negativity, I can't really think of any invariants that must hold *during* route generation.

**Comment by CyberiaResurrection** [comment]
@tjoneslo , I can add a couple of during-generation invariants now:
Any given route from star A to star B is generated at most once;
Route and weights must be strictly positive;

**Comment by tjoneslo** [comment]
Have you added all of these checks into the code?

**Comment by CyberiaResurrection** [comment]
The during generation stuff, yes.  The galaxy-level balancing stuff, not yet - that's in BalanceCalcNumbers branch
