### ISSUE TITLE
Font paths are hard coded into the SubsectorMap.py

### ISSUE THREAD

**Issue by tjoneslo** [makhidkarun/traveller_pyroute#18]
`SubsectorMap.py` the code that draws the graphic subsector maps uses hard coded paths for the fonts it needs. This work correctly for Ubuntu (my system), but not for Fedora or Centos. It also assume the fonts are installed in the standard location (via the apt-get package). 

https://github.com/makhidkarun/traveller_pyroute/blob/master/PyRoute/SubsectorMap.py#L35-L42

We should have a way of finding the paths for the needed fonts and failing gracefully with good error messages if the needed fonts are not found. 

This command line will return a list of paths for the fonts. The `fc-list` command is part of the `fontconfig` package, so be sure to request users install this as well. 

`fc-list -f '%{file}\n' DejaVuSerifCondensed`

Unfortunately PyPi does not seem to have a easily found / usable font manager package.

**Comment by tjoneslo** [comment]
According to the wisdom of the internet all version so Linus use either `/etc/fonts/fonts.conf` an/or  `/etc/fonts/local.conf` to list the directories where fonts are to be found, These are XML files so they need to be parsed with an XML parser. 

The MathPlotLib Python library has a font manager emended, but that seems heavy weight to have as a dependency. 

Pyglet is another library used for game development which has a font manager, but is also very large dependency.

**Comment by LeamHall** [comment]
Haven't looked at the code yet, so I'm not sure why font specification is needed at all. Will Windows or Mac users have the same issue?

**Comment by tjoneslo** [comment]
The code uses Pillow (a fork of the Python Image Library) to generate subsector maps as PNG images. Pillow doesn't include a font manager, you have to supply hard coded paths to the font files so you can use fonts to render text on the images. An on every OS these paths are different and there is no solid way to determine what these paths are supposed to be.

**Comment by CyberiaResurrection** [comment]
@tjoneslo , I added FontLayer.py a while back - does that class address this issue well enough for this to be closed?

**Comment by tjoneslo** [comment]
FontLayer gets the job done. Closing,
