### ISSUE TITLE
ImportError: no module named networkx

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#2]
When trying to do a single-sector run (smoke test before letting rip with the whole shebang), I get the following in route.log:

Traceback (most recent call last):
  File "PyRoute/route.py", line 13, in <module>
    from Galaxy import Galaxy
  File "/home/alex/Documents/travmaps/pyroute/PyRoute/Galaxy.py", line 12, in <module>
    import networkx as nx
ImportError: No module named networkx

This happens, despite the following when driving python from its command line:
Python 2.7.13 (default, May 10 2017, 20:04:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> G=nx.Graph()
>>> G.add_edge(1,2)
>>> print G.nodes()
[1, 2]
>>> quit()

What am I doing wrong?

**Comment by CyberiaResurrection** [comment]
A little update - after redoing the install of networkx, things now get past the import stage under both python2 and python3, but still blow up good under pypy and pypy3

**Comment by tjoneslo** [comment]
Pypy needs a separate install using `pypy pip install ...` Or at least that's what I discovered. I spent so much time hassling around with the install to get this to work on the local and DO machines I no longer remember all the exact steps.

**Comment by CyberiaResurrection** [comment]
Ok,

**Comment by CyberiaResurrection** [comment]
When installing Pillow under pypy, I've had to also bolt in (via dnf install) following packages, since under pypy, Pillow seems to get built from source:
`zlib-devel`
`libjpeg-turbo-devel`
`python-devel`

Still not there yet, since build process is jumping up and down complaining Python.h is MIA.

**Comment by tjoneslo** [comment]
`python.h` is installed as part of the python-devel package (if you are on linux). I'm not sure how you get that on Windows.
