### ISSUE TITLE
Update / Fix some missing allegiance codes

### ISSUE THREAD

**Issue by tjoneslo** [makhidkarun/traveller_pyroute#23]
The following are changes to allegiance codes that don't work correctly with the current PyRoute:

* `Kc` is a "K'kree Client state and should be a non-aligned 
* The sophont code for the K'kree is "KXkr, which only affects the upload to the wiki. 
* The SELK allegiance should have a default sophont code of "Lith" (Lithkin)
* The Krotan Protectorate (KrPr) should have a default sophont code of "Krot" (Krotan)
* Droyne worlds (Dr, NaDr) should have a default sophont code of "Droy" (Droyne) 
* Worlds of Taakas Yh'Drak (TY) should have a default sophont code of "Drak" (Drakaran)
* Add a "----" (four dash) unaligned, unpopulated world 
* Add a "NaZh" for a non-aligned Zhodani world with a default sophont code of "Zhod" 
* Add a "NaHu" for a non-aligned Human dominated world with a default sophont code "Huma"
*

**Comment by CyberiaResurrection** [comment]
time to close this, @tjoneslo ?
