### ISSUE TITLE
Sample runtimes on front page haven't been touched in 8 years

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#31]
So here's some fresher data, after some wombat hoicked out some of the superfluous computation.
Run times are overall, including map generation, without profiling enabled.  I haven't even _looked_ at speeding up map generation or data load.

Full sector:
Lishun - 601 stars, 66 seconds (57 seconds pathfinding)
Dagudashaag - 552 stars, 57 seconds (45 seconds pathfinding)
Solomani Rim - 400 stars, 58 seconds (44 seconds pathfinding)

Multiple Sectors:
Domain of Sylea - Core, Fornast, Massilia, Delphi: 1,926 stars, 705 seconds (660 seconds pathfinding)
Zhodani Consulate Heartland - Zdiedeiant, Stiatlchepr, Zhdant, Tienspevnkr: 2231 worlds, 845 seconds (740 seconds pathfinding)

Implist.txt (32 sectors):
13,370 stars, 13,930 seconds (3 h 52 min 10 s), (13,468 seconds pathfinding - 3 h 44 min 28 s)

Up To Eleven (all 142 charted-space sectors):
51,190 stars, 44,727 seconds (12 h 25 min 27 s), (43,853 seconds pathfinding - 12 h 10 min 53 s)

Fraction of time taken in pathfinding
Lishun - 86.4%
Dagudashaag - 78.9%
Solomani Rim - 75.9%
Domain of Sylea - 93.6%
Zhodani Consulate Heartland - 87.6%
Implist.txt - 96.7%
Up To Eleven - 98.0%

I doubt it's much of a surprise to find out that pathfinding still dominates overall route calculation time.

**Comment by tjoneslo** [comment]
I'm not sure anyone is capable of reproducing these results exactly, but I'd love to try at some point. But yes. please put together a PR for this

**Comment by CyberiaResurrection** [comment]
OK, cool - I'll see if travmap has landed any new sectors, slurp them, and set to re-running things.

Unless you've got other ideas, I'll round off to similar granularities as what's on the front page now - single-sector to nearest 10 seconds, T5SS to nearest 10 minutes, etc.

**Comment by tjoneslo** [comment]
Just did the Imperial Sectors: 12,435s (3 hours, 27 minutes, and 15 seconds)  overall, 12,147s (3 hours, 22 minutes, and 27 seconds) route finding. Running with PyPy

**Comment by CyberiaResurrection** [comment]
That bodes well, being about what I got for the imperial sectors.  Have you run for smaller regions yet?

**Comment by CyberiaResurrection** [comment]
This is teasing at upcoming work I've got in a branch I'm yet to push:

Lishun sector
601 stars
27 seconds total
1 second jump generation
6 seconds pathfinding

Dagudashaag sector
559 stars
28 seconds total
1 second jump generation
8 seconds pathfinding

Solomani Rim sector
400 stars
27 seconds total
1 second jump generation
18 seconds pathfinding

Domain of Sylea
1,926 stars
107 seconds total
8 seconds jump generation
66 seconds pathfinding

Zhodani Consulate heartland
1,656 stars
71 seconds total
6 seconds jump generation
42 seconds pathfinding

Imperial sectors
13,370 stars
2,464 seconds total
279 seconds jump generation
1,950 seconds pathfinding

Up To Eleven (all 163 charted-space sectors)
58,606 stars
22,226 seconds total
4,176 seconds jump generation
17,182 seconds pathfinding

**Comment by CyberiaResurrection** [comment]
Fixed in #124 , closing this issue
