### ISSUE TITLE
Trade codes don't extract sophont codes with apostrophes

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#35]
Assuming the following unit test is well formed:
```
        code = TradeCodes("Ag S'mr1 Huma4")
        self.assertFalse(code.homeworld)
        self.assertEqual(['S\'mr1', 'Huma4'], code.sophonts)
        self.assertEqual(['Ag'], code.codeset)
```
It blows up on [master HEAD as at this issue being opened](https://github.com/makhidkarun/traveller_pyroute/commit/81e8cd3b1257da15cb60868e3f0ec17ead1b06d4), complaining that code.sophonts is ```[`Huma4`]``` instead of ```[`Huma4`, 'S'mr1']```.

At first shufti, it seems to be down to the sophont-list detection in TradeCodes.py, line 46:
```
        self.sophont_list = [code for code in self.codes if re.match(r"\w{4}(\d|W)", code, re.U)]
```

My regex-fu is pretty pants, but the simplest fix I can see is expanding that ```\w``` in the regex to ```[\w\']``` to match any word character or an apostrophe.

**Comment by CyberiaResurrection** [comment]
https://travellermap.com/doc/secondsurvey#remarks lists four listed sophont codes containing apostrophes:
K'kr - K'kree
Mal' - Mal'Gnar
S'mr - S'mrii
Za't - Za'tachk

**Comment by tjoneslo** [comment]
You are correct, and that is the proper fix. I'll need to update that in the code at some point.

**Comment by CyberiaResurrection** [comment]
This looks like a two commit fix - first, characterise by separately feeding in each defined T5SS sophont codes and checking they each end up as sophont codes per TradeCode, then land the regex fix you've OKed.

I could slide this in underneath delta debugging (and rebase delta debugging atop the new master HEAD afterwards) if that works for you, or would that be piling too much outstanding work up?

**Comment by tjoneslo** [comment]
I would prefer to keep it as a separate Pull Request. Allows tracking issues and fixes better

**Comment by CyberiaResurrection** [comment]
That's what I was proposing - a separate PR that gets rolled up ahead of the delta debug PR.  Said delta debug PR then gets rebased (by me - it's easy enough) on top of the new (with-sophont-code-fix) master HEAD to keep the repo history nice and clean.
