### ISSUE TITLE
Where is SpeculativeTrade defined?

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#7]
When I try to run route.py along the lines of what's outlined in RunSuite.txt (converted to use python, as I am apparently _programmer non grata_ to PyPy), it blows up with an ImportError, namely:

`
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/route.py", line 14, in <module>
    from SpeculativeTrade import SpeculativeTrade
ImportError: No module named SpeculativeTrade
`

**Comment by tjoneslo** [comment]
I was missing adding that to the repo. I've updated the code and added that module to the master branch. 

Please verify this all works as expected.

**Comment by CyberiaResurrection** [comment]
Yes, that appears to have fixed that one up - SpeculativeTrade is now there and gets picked up fine.
