### ISSUE TITLE
Sector file download broken

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#8]
When I try to use downloadsec.py as outlined in RunSuite, I get:

```
[alex@localhost traveller_pyroute]$ python PyRoute/downloadsec.py --routes sectorlist.txt  ../sectors
Downloading Afawahisa
Traceback (most recent call last):
  File "PyRoute/downloadsec.py", line 52, in <module>
    get_url (url, sector, 'sec')
  File "PyRoute/downloadsec.py", line 29, in get_url
    with codecs.open(path, 'wb', 'utf-8') as out:
  File "/usr/lib64/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'../sectors/Afawahisa.sec'
```

**Comment by CyberiaResurrection** [comment]
Running the same command under a debugger clears the problem, but that's not particularly sustainable long-term.

**Comment by tjoneslo** [comment]
The reason for the `IOError: [Errno 2] No such file or directory` error is the directory `../sectors` does not exist. Given that is a relative path, it may not be in the place you expect.

**Comment by CyberiaResurrection** [comment]
Weird - the ```../sectors``` directory definitely does exist, using ```../PyRoute``` as working directory.  Route calculation references ```../sectors``` and ```../maps``` without missing a beat.

**Comment by CyberiaResurrection** [comment]
Heck with it, it will be a pain to remember to use the debugger, but it's a workaround.  Closing.
